<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Fix\acceptor.cfg" />
    <None Remove="Fix\FIX44.xml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Fix\acceptor.cfg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Fix\FIX44.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="QuickFIXn.FIX4.4" Version="1.13.0" />
  </ItemGroup>

</Project>
